---
# Pi Cluster variables

#######
# K3S #
#######

# k3s version
k3s_version: v1.28.2+k3s1

# k3s shared token
token: "{{ vault.cluster.k3s.token }}"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: ""
extra_agent_args: ""