---

- name: Generate vault variables file
  hosts: localhost

  tasks:
    - name: Create random passwords
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      with_items:
        - k3s_token

    - name: Generate vault file
      ansible.builtin.template:
        src: vars/vault.yml.j2
        dest: vars/vault.yml

    - name: Encrypt file
      ansible.builtin.command:
        cmd: ansible-vault encrypt --vault-password-file=./.vault/vault-pass.sh vars/vault.yml
