---
all:
  children:
    raspberrypis:
      hosts:
        node1: 
          ansible_user: pi
          ansible_host: 192.168.0.100
        node2:
          ansible_user: pi
          ansible_host: 192.168.0.101
    k3s_cluster:
      children:
        server:
            hosts:
              node1:
        agent:
            hosts:
              node2:
      vars:
        ansible_port: 22
        ansible_user: debian
        k3s_version: v1.26.9+k3s1
        token: "mytoken"  # Use ansible vault if you want to keep it secret
        api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
        extra_server_args: ""
        extra_agent_args: ""