---
all:
  children:
    raspberrypis:
      hosts:
        pi5: 
          ansible_user: pi
          ansible_host: 192.168.0.100
        pi4:
          ansible_user: pi
          ansible_host: 192.168.0.101
    k3s_cluster:
      children:
        server:
            hosts:
              pi5:
        agent:
            hosts:
              pi4:
