---
all:
  children:
    raspberrypis:
      hosts:
        master:
          ansible_user: pi
          ansible_host: 192.168.0.100
        node1:
          ansible_user: pi
          ansible_host: 192.168.0.101

