## Roles to install K3S on a Raspberry Pi cluster: https://github.com/k3s-io/k3s-ansible
---
- name: Install K3S prerequisites
  hosts: k3s_cluster
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/prereq
    - role: k3s/roles/airgap
    - role: k3s/roles/raspberrypi

- name: Install K3S master node
  hosts: server
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/k3s_server

- name: Install K3S worker nodes
  hosts: agent
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/k3s_agent

# - name: Label K3S worker nodes
#   hosts: k3s_master
#   tags: [config]
#   pre_tasks:
#     - name: Include vault variables
#       include_vars: "vars/vault.yml"
#       tags: ["always"]
#     - name: Include picluster variables
#       include_vars: "vars/picluster.yml"
#       tags: ["always"]
#   tasks:
#     - name: "Wait for worker nodes to be ready"
#       command:
#         cmd: "kubectl get nodes {{ item }}"
#       register: nodes
#       until:
#         - '" Ready "  in nodes.stdout'
#       retries: 10
#       delay: 5
#       with_items: "{{ groups['k3s_worker'] }}"

#     - name: label k3s worker nodes
#       command:
#         cmd: "kubectl label nodes {{ item }} kubernetes.io/role=worker"
#       with_items: "{{ groups['k3s_worker'] }}"

# - name: Get Kubernets config file
#   hosts: k3s_master
#   tags: [kube-config]
#   tasks:
#     - name: Get k3s config file
#       run_once: true
#       ansible.builtin.slurp:
#         src: /etc/rancher/k3s/k3s.yaml
#       register: kubeconfig_base64

#     - name: Write Kubernetes config file with the correct cluster address
#       ansible.builtin.copy:
#         content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', k3s_api_vip ) }}"
#         dest: "~/.kube/config"
#         mode: 0600
#       delegate_to: localhost
#       run_once: true
