## Roles to install K3S on a Raspberry Pi cluster: https://github.com/k3s-io/k3s-ansible
---
- name: Install K3S prerequisites
  hosts: k3s_cluster
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/prereq
    - role: k3s/roles/airgap
    - role: k3s/roles/raspberrypi

- name: Install K3S master node
  hosts: server
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/k3s_server

- name: Install K3S worker nodes
  hosts: agent
  become: true
  pre_tasks:
    - name: Include vault variables
      include_vars: "vars/vault.yaml"
    - name: Include picluster variables
      include_vars: "vars/picluster.yaml"
  roles:
    - role: k3s/roles/k3s_agent
