---

- name: Generate vault variables file
  hosts: localhost

  tasks:
    - name: Create random passwords
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits' ) }}"
      with_items:
        - k3s_token

    - name: Generate vault file
      ansible.builtin.template:
        src: vars/vault.yaml.j2
        dest: vars/vault.yaml

    - name: Encrypt file
      ansible.builtin.command:
        cmd: ansible-vault encrypt vars/vault.yaml

- name: Get Roles
  hosts: localhost
  tasks:
    - name: Get K3S Ansible roles
      ansible.builtin.git:
        repo: https://github.com/k3s-io/k3s-ansible.git
        dest: /usr/share/ansible/roles/k3s
